server:
  port: 8081

spring:
  application:
    name: "CrediYaMsRequests"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  kafka:
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "CrediYaMsRequests"

adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "crediya_requests"
    schema: "public"
    username: "crediya_user"
    password: "+70Ou9gX@5d7"
  kafka:
    consumer:
      topic: "${DEBEZIUM_TOPIC_PREFIX:crediya.auth}.public.users"
      auto-offset-reset: "earliest"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "when-authorized"
  health:
    circuitbreakers:
      enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

adapter:
  restconsumer:
    timeout: 5000
    url: "http://localhost:8080"
  sqs:
    region: "us-east-1"
    queueUrl: "https://sqs.us-east-1.amazonaws.com/664751201274/RequestStatusQueue"
resilience4j:
  circuitbreaker:
    instances:
      getUserByDocumentNumber:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"

security:
  jwt:
    secret: "ZGV2ZWxvcG1lbnRfc2VjcmV0X2tleV9mb3JfandoX3Rva2VuX2dlbmVyYXRpb25fY3JlZGl5YV9taWNyb3NlcnZpY2VzXzIwMjQ="
